# Form implementation generated from reading ui file 'mainwindow4.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from Controlers.user_controller import UserController
from Views.first_page import Ui_Firstpage

class ForgetPassword(object):
    def __init__(self):
        self.user_password=""
        self.username_save=""
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(334, 400)

        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.forget_l = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lalezar")
        font.setPointSize(25)
        self.forget_l.setFont(font)
        self.forget_l.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.forget_l.setObjectName("forget_l")
        self.verticalLayout_2.addWidget(self.forget_l)

        self.background = QtWidgets.QLabel(parent=self.centralwidget)
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("pictures/lock.PNG"))
        self.background.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.background.setObjectName("background")
        self.verticalLayout_2.addWidget(self.background)

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.question_le = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.question_le.setPlaceholderText("What is your favorite color ? ")
        self.verticalLayout.addWidget(self.question_le)

        self.username_le = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.username_le.setPlaceholderText("Username")
        self.verticalLayout.addWidget(self.username_le)

        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.clicked.connect(self.next_clicked)
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 334, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.controller = UserController(self)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.forget_l.setText(_translate("MainWindow", "Forget Password"))
        self.pushButton.setText(_translate("MainWindow", "Next ->"))
    
    def next_clicked(self):
        if self.controller.forget_password(self.username_le.text(),self.question_le.text().lower()):
            self.username_save=self.username_le.text()
            user_email=self.controller.get_email(self.username_le.text())
            self.user_password=self.controller.send_email(user_email)
            self.question_le.hide()
            self.username_le.setText("")
            self.username_le.setObjectName("password")
            self.username_le.setPlaceholderText("Password")
            self.pushButton.setText("Check Password")
            self.pushButton.clicked.connect(lambda: self.check_password(self.username_le.text()))
    def check_password(self,password):
        print(password,self.user_password)
        if password == self.user_password:
            user_password=self.controller.get_password(self.username_save)
            self.show_information(f"Your Password is {user_password}")
            
    def show_information(self, message: str) -> None:
        """make a messagebox to show errors to user.

        Args:
            message (str): It's an error message that when inputs are invalid throw.
        """
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Icon.Information)
        msg.setText(message)
        msg.setWindowTitle("Error")
        msg.exec()
            

            


