# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Pics(QtWidgets.QLabel):
    def __init__(self, parent, type, pic, width, height):
        super().__init__(parent=parent)
        pixmap = QtGui.QPixmap(pic)
        if width and height:
            pixmap = pixmap.scaled(width, height, QtCore.Qt.AspectRatioMode.KeepAspectRatio, QtCore.Qt.TransformationMode.SmoothTransformation)
        self.setPixmap(pixmap)

class Ui_Setting(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(764, 503)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)

        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)

        self.verticalLayout_8 = QtWidgets.QVBoxLayout()

        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()

        self.verticalLayout_7 = QtWidgets.QVBoxLayout()

        self.verticalLayout = QtWidgets.QVBoxLayout()

        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.username_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.verticalLayout_3.addWidget(self.username_lbl)

        self.pic_lbl = Pics(self.centralwidget,"Set Pic","?",None,None)
        self.verticalLayout_3.addWidget(self.pic_lbl)
        self.verticalLayout.addLayout(self.verticalLayout_3)

        self.add_pic_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_pic_btn.clicked.connect(self.choosing_pic)
        self.verticalLayout.addWidget(self.add_pic_btn)
        self.verticalLayout_7.addLayout(self.verticalLayout)

        self.line_4 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.verticalLayout_7.addWidget(self.line_4)

        self.horizontalLayout = QtWidgets.QHBoxLayout()

        self.theme_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.horizontalLayout.addWidget(self.theme_lbl)

        self.theme_combo = QtWidgets.QComboBox(parent=self.centralwidget)
        self.theme_combo.addItem("")
        self.theme_combo.addItem("")
        self.horizontalLayout.addWidget(self.theme_combo)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()

        self.menu_lbl = QtWidgets.QLabel(parent=self.centralwidget)

        self.menu_combo = QtWidgets.QComboBox(parent=self.centralwidget)

        self.horizontalLayout_18.addWidget(self.menu_combo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19.addLayout(self.verticalLayout_7)
        self.line_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)

        self.horizontalLayout_19.addWidget(self.line_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()

        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.username_lbl_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.horizontalLayout_6.addWidget(self.username_lbl_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.id_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.horizontalLayout_2.addWidget(self.id_lbl)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.verticalLayout_2.addWidget(self.line)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.email_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.horizontalLayout_3.addWidget(self.email_lbl)

        self.le_email = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.horizontalLayout_3.addWidget(self.le_email)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.phone_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.horizontalLayout_4.addWidget(self.phone_lbl)

        self.le_phone = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.horizontalLayout_4.addWidget(self.le_phone)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()

        self.firstname_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.horizontalLayout_7.addWidget(self.firstname_lbl)

        self.le_firstname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.horizontalLayout_7.addWidget(self.le_firstname)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)

        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.lastname_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.horizontalLayout_9.addWidget(self.lastname_lbl)

        self.le_lastname = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.horizontalLayout_9.addWidget(self.le_lastname)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)

        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.password_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.horizontalLayout_10.addWidget(self.password_lbl)

        self.le_password = QtWidgets.QLineEdit(parent=self.centralwidget)

        self.horizontalLayout_10.addWidget(self.le_password)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.verticalLayout_2.addWidget(self.line_2)

        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()

        self.city_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.horizontalLayout_11.addWidget(self.city_lbl)

        self.le_city = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.horizontalLayout_11.addWidget(self.le_city)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)

        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.sequrity_q_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.sequrity_q_lbl.setObjectName("sequrity_q_lbl")
        self.horizontalLayout_12.addWidget(self.sequrity_q_lbl)
        self.le_security_q = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.le_security_q.setObjectName("le_security_q")
        self.horizontalLayout_12.addWidget(self.le_security_q)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.birthday_lbl = QtWidgets.QLabel(parent=self.centralwidget)
        self.birthday_lbl.setObjectName("birthday_lbl")
        self.horizontalLayout_13.addWidget(self.birthday_lbl)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(parent=self.centralwidget)
        self.dateTimeEdit.setMaximumDate(QtCore.QDate(2005, 12, 31))
        self.dateTimeEdit.setMinimumDate(QtCore.QDate(1920, 9, 14))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_13.addWidget(self.dateTimeEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_19.addLayout(self.verticalLayout_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.line_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_8.addWidget(self.line_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.save_info_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.save_info_btn.setObjectName("save_info_btn")
        self.verticalLayout_4.addWidget(self.save_info_btn)
        self.del_user_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.del_user_btn.setObjectName("del_user_btn")
        self.verticalLayout_4.addWidget(self.del_user_btn)
        self.export_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.export_btn.setObjectName("export_btn")
        self.verticalLayout_4.addWidget(self.export_btn)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.verticalLayout_8.addLayout(self.verticalLayout_4)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 764, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.username_lbl.setText(_translate("MainWindow", "username"))
        self.pic_lbl.setText(_translate("MainWindow", "pic"))
        self.add_pic_btn.setText(_translate("MainWindow", "Upload Picture"))
        self.theme_lbl.setText(_translate("MainWindow", "Theme:"))
        self.theme_combo.setItemText(0, _translate("MainWindow", "Dark"))
        self.theme_combo.setItemText(1, _translate("MainWindow", "Light"))
        self.menu_lbl.setText(_translate("MainWindow", "Menu Position:"))
        self.username_lbl_4.setText(_translate("MainWindow", "username"))
        self.id_lbl.setText(_translate("MainWindow", "id"))
        self.email_lbl.setText(_translate("MainWindow", "Email"))
        self.le_email.setPlaceholderText(_translate("MainWindow", "New email..."))
        self.phone_lbl.setText(_translate("MainWindow", "Phone"))
        self.le_phone.setPlaceholderText(_translate("MainWindow", "New phone number..."))
        self.firstname_lbl.setText(_translate("MainWindow", "First name"))
        self.le_firstname.setPlaceholderText(_translate("MainWindow", "New first name..."))
        self.lastname_lbl.setText(_translate("MainWindow", "Last name"))
        self.le_lastname.setPlaceholderText(_translate("MainWindow", "New last name..."))
        self.password_lbl.setText(_translate("MainWindow", "Password"))
        self.le_password.setPlaceholderText(_translate("MainWindow", "New password..."))
        self.city_lbl.setText(_translate("MainWindow", "City"))
        self.le_city.setPlaceholderText(_translate("MainWindow", "New city..."))
        self.sequrity_q_lbl.setText(_translate("MainWindow", "Security question"))
        self.le_security_q.setPlaceholderText(_translate("MainWindow", "What\'s your favorite color?..."))
        self.birthday_lbl.setText(_translate("MainWindow", "Birthday"))
        self.dateTimeEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.save_info_btn.setText(_translate("MainWindow", "Save Changes"))
        self.del_user_btn.setText(_translate("MainWindow", "Delete User"))
        self.export_btn.setText(_translate("MainWindow", "Export to CSV"))
        self.pushButton_3.setText(_translate("MainWindow", "Clear Transactions"))
    def choosing_pic(self):
        options=QtWidgets.QFileDialog.Option.ReadOnly
        file_name, _ = QtWidgets.QFileDialog.getOpenFileName(self, "Select a File", "",
                                                       "All Files (*);;Text Files (*.txt);;Python Files (*.py)",
                                                       options=options)
        self.verticalLayout_3.removeWidget(self.pic_lbl)
        self.pic_lbl.deleteLater()

        # Create a new Pics widget
        self.pic_lbl = Pics(self.centralwidget, "Set Pic", r"{R}".format(R=file_name),200,200)

        # Add the new Pics widget to the layout
        self.verticalLayout_3.addWidget(self.pic_lbl)